# Generated by Django 2.2 on 2021-05-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CR', 'carryout'), ('DL', 'delivery')], default='DL', max_length=2)),
                ('qty', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('adress', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(default=1, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='myappfinal.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('VG', 'veggie'), ('PP', 'pepperoni'), ('MG', 'margherita'), ('BQ', 'bbq'), ('HV', 'hawaiian'), ('BF', 'buffalo'), ('SP', 'supreme')], default='VG', max_length=2)),
                ('size', models.CharField(choices=[('LG', 'large'), ('MD', 'medium'), ('SM', 'small')], default='MD', max_length=2)),
                ('crust', models.CharField(choices=[('TC', 'thin_crust'), ('TCK', 'thick_crust')], default='TC', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='myappfinal.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='favorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='myappfinal.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='myappfinal.User'),
        ),
    ]
