# Generated by Django 2.2 on 2021-05-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappfinal', '0005_auto_20210530_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('Carryout', 'carryout'), ('Delivery', 'delivery')], default='Delivery', max_length=25),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('THIN CRUST', 'thin_crust'), ('THICK CRUST', 'thick_crust')], default='THIN CRUST', max_length=32),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('LARGE', 'large'), ('MEDIUM', 'medium'), ('SMALL', 'small')], default='MEDIUM', max_length=25),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='types',
            field=models.CharField(choices=[('VEGETERIAN', 'veggie'), ('PEPPERONI', 'pepperoni'), ('MARGHERITA', 'margherita'), ('BARBEQUE', 'bbq'), ('HAWAIIAN', 'hawaiian'), ('BUFFALO', 'buffalo'), ('SUPREME', 'supreme')], default='VEGETERIAN', max_length=25),
        ),
    ]
