# Generated by Django 2.2 on 2021-05-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappfinal', '0006_auto_20210530_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
